### ISSUE TITLE
Installation author not verified

### ISSUE THREAD

**Issue by manish-juneja** [mozilla/lightbeam#664]
When you try to install Lightbeam , the author for the content comes out not to be verified which is a bit skeptical as the author is Mozilla itself. Installation link just in case(if i am going for the wrong link) ->
https://addons.mozilla.org/en-US/firefox/addon/lightbeam/
Thanks

**Comment by fmarier** [comment]
If I recall correctly, that feature (author signing their packages) has never really been used much. I'm surprised it's still shown in the Firefox UI actually since it is confusing to users as you rightfully point out.

Lightbeam itself is always verified by Mozilla to some extent since it goes through a review process and then gets delivered over HTTPS from `addons.mozilla.org`. In addition, `addons.mozilla.org` will soon be introducing add-on signing which will be an extra layer of protection.
