### ISSUE TITLE
Detect if history or cookies are disabled

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#668]
Lightbeam doesn't work when cookies are disabled (#490) or when history is disabled (#463).

We should detect these settings and show a message to the user instead of just showing a blank graph.

**Comment by monicachew** [comment]
The cookie thing is an easy pref check on network.cookie.cookieBehavior. It looks like history may be browser.history.allow{Push,Pop}State, or places.history.enabled. Does it fail on history because all forms of local storage are disabled?

We still get third party connections from AJAX requests, not just cookies, right? So it is possible that there will be graph data if cookies are disabled but most likely won't look like the user expects.

**Comment by jonathanKingston** [comment]
We now work for this case, we choose not to show cookies as fingerprinting is way more common now. (feel free to create an issue about adding it back in, the simplicity is pretty great IMO though).
